# ----- dev -----
spring.datasource.url=jdbc:postgresql://localhost:5433/gym_crm_dev
spring.datasource.username=postgres
spring.datasource.password=devpass

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Health (optional if you have a dev upstream)
management.endpoint.health.show-details=always
health.external-api.url=http://example.com

