# ----- dev -----
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=password
spring.security.user.name=admin
spring.security.user.password=password
spring.security.user.roles=USER


# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Health (optional if you have a dev upstream)
management.endpoint.health.show-details=always
health.external-api.url=http://example.com


logging.level.org.example.security.BruteForceProtectionService=DEBUG
logging.level.org.example.security=DEBUG
