# ----- dev -----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Health
management.endpoint.health.show-details=when_authorized
health.external-api.url=${EXT_HEALTH_URL:https://dev-api.example.com/health}
health.external-api.required=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
