# ----- local -----

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Health details visible in local
management.endpoint.health.show-details=always

# External API health
health.external-api.url=https://httpstat.us/200
health.external-api.required=false

# Uploads health
health.uploads.path=./uploads
health.uploads.min-free-mb=50
health.uploads.autocreate=true

# SQL logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
