# ----- prod -----
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_prod
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Actuator on side port
management.server.port=8081


# Trim logs a bit
logging.level.org.springframework=info
logging.level.org.hibernate.SQL=info
