# ----- stg -----
spring.jpa.hibernate.ddl-auto=validate

# Actuator on a side port
management.server.port=8081
management.endpoint.health.show-details=when_authorized
management.endpoints.web.exposure.include=health,info,metrics,prometheus

health.external-api.required=true

# Reduce logs
logging.level.org.hibernate.SQL=info
logging.level.org.springframework=info
