# ----- common defaults -----
spring.application.name=gym-crm
spring.jpa.open-in-view=false

# Actuator/metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true

# DB URL (shared everywhere)
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm

# Load file
spring.config.import=optional:file:./config/db-secrets.properties

# Prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

# Local by default
spring.profiles.default=local
