# ----- prod -----
spring.jpa.hibernate.ddl-auto=validate

# Actuator on internal port
management.server.port=8081
management.endpoint.health.show-details=when_authorized
management.endpoints.web.exposure.include=health,info,metrics,prometheus

health.external-api.required=true

# Logging
logging.level.root=info
