# ----- stg -----
spring.datasource.url=jdbc:postgresql://localhost:5434/gym_crm_stg
spring.datasource.username=postgres
spring.datasource.password=stgpass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Actuator on side port
management.server.port=8081



