# ----- common defaults -----
spring.application.name=gym-crm
spring.jpa.open-in-view=false

# Actuator/metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

# JWT settings
jwt.secret=e2b46d0f7c3a95ab5f9c6e2a47b1d0c98f47e9c5b1a26d38c4f9d12c0e7a54fb
jwt.expiration=3600000
