# ------------------------------
# Server Configuration
# ------------------------------
server.port=8082

# ------------------------------
# Application Info
# ------------------------------
spring.application.name=trainer-workload-ms

# ------------------------------
# Database (H2 in-memory)
# ------------------------------
spring.datasource.url=jdbc:h2:mem:workload;DB_CLOSE_DELAY=-1

# ------------------------------
# JPA / Hibernate
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ------------------------------
# Eureka Client
# ------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ------------------------------
# Logging
# ------------------------------


# JWT settings
jwt.secret=e2b46d0f7c3a95ab5f9c6e2a47b1d0c98f47e9c5b1a26d38c4f9d12c0e7a54fb
jwt.expiration=3600000


# ---- Feign client timeouts ----
feign.client.config.default.connectTimeout=3000     # 3 seconds
feign.client.config.default.readTimeout=5000        # 5 seconds
feign.client.config.default.loggerLevel=full


# Disable Zipkin exporting
management.tracing.enabled=true
management.zipkin.tracing.export.enabled=false